### ISSUE TITLE
Windows location for override.yml

### ISSUE THREAD

**Issue by fgroenendijk** [nginxinc/nginx-ingress-workshops#3]
I'm not sure how to check this is correct, but there is a vtunnel-config.yaml file in the folder %AppData%\rancher-desktop. I've placed the override.yml there. Again I do not know how to check if this is the correct location. Is there a command to run to see if the klipper loadbalancer is running?

**Comment by chrisakker** [comment]
Not sure of the actual klipper details, perhaps the docs can provide some answers:  https://docs.k3s.io/networking
